import Layout from '../components/layouts/Layout'
import '../styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  // openGraph: {
  //   images: 'https://www.linkpicture.com/q/Неозаглавен-1440-t-1440-пиксела.png',
  //   thumnail: "https://www.linkpicture.com/q/Неозаглавен-1440-t-1440-пиксела.png"
  // },
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      
      <body>
      <Layout>
        {children}
        </Layout>
      </body>
    </html>
  )
}
